name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cmake -Bbuild
      - run: cmake --build build --target Salsa20Tests
      - working-directory: ./build
        run: ctest --timeout 86400